name: Merge

on:
  workflow_dispatch:

jobs:
  merge-dev-onto-master:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
            fetch-depth: 0
      - name: merge
        run: |
          git fetch origin
          git checkout dev
          git pull
          git checkout master
          git pull
          git rebase dev
          git push
