name: Deploy (Merge and Build)

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE: ghcr.io/${{ github.repository }}
  
jobs:
  merge-dev-onto-master:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
            fetch-depth: 0

      - name: Set up Git user
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "actions@github.com"

      - name: Merge dev onto master
        run: |
          git fetch origin
          git checkout dev
          git pull
          git checkout master
          git pull
          git rebase dev
          git push origin master
          
  build-and-push-image:
      runs-on: ubuntu-latest
      permissions:
        contents: read
        packages: write
        attestations: write
        id-token: write
      steps:
        - name: Checkout repository
          uses: actions/checkout@v4
        - name: Log in to the Container registry
          uses: docker/login-action@v3
          with:
            registry: ${{ env.REGISTRY }}
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
        - name: Build and push Docker image
          uses: docker/build-push-action@v6
          with:
            context: .
            push: true
            tags: |
              ${{ env.IMAGE }}:latest
              ${{ env.IMAGE }}:${{ github.run_number }}
