name: Merge

on:
  workflow_dispatch:

jobs:
  merge-dev-onto-master:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: merge
        run: |
          git switch dev
          git pull
          git switch master
          git pull
          git rebase dev
          git push
