name: merge

on:
  workflow_dispatch:

jobs:
  merge-dev-onto-master:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: merge
        run: |
          git checkout dev
          git pull
          git checkout master
          git pull
          git rebase dev
          git push
