name: Merge dev onto master

on:
  workflow_dispatch:

jobs:
  merge-dev-onto-master:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
            fetch-depth: 0
            persist-credentials: false

      - name: Set up Git user
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "actions@github.com"

      - name: Merge dev onto master
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          git fetch origin
          git checkout dev
          git pull
          git checkout master
          git pull
          git rebase dev
          git push origin master
