name: Runs workflow on push to master

on:
  push:
    branches: ['master']
  workflow_dispatch:

jobs:
  test-on-push:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
